version: '3'
services:
    user_db:
        volumes:
            - ./var/tests/redis:/data
    s3_like:
        volumes:
            - ./var/tests/minio/config:/root/.minio
            - ./var/tests/minio/volumes:/export
        environment:
            MINIO_ACCESS_KEY: test_s3_access_key
            MINIO_SECRET_KEY: test_s3_secret_key
